const { GoogleGenAI } = require('@google/genai');

const API_KEY = process.env.GEMINI_API_KEY;

// Mock Fallback generator to prevent breaking UI if key is missing
const simulatedAiDetection = (text) => {
    // Generate a random score for demo purposes when no key is present
    const aiDetectionScore = Math.floor(Math.random() * 100);
    return {
        aiDetectionScore: aiDetectionScore,
        isAiGenerated: aiDetectionScore > 50,
        analysis: "This is a simulated analysis because a real Gemini API key is not yet configured."
    };
};

const analyzeTextWithAI = async (text) => {
    // Use fallback if key is missing or mock
    if (!API_KEY || API_KEY === 'mock_gemini_key') {
        return simulatedAiDetection(text);
    }

    try {
        console.log("Analyzing text with Google Gemini AI...");
        const ai = new GoogleGenAI({ apiKey: API_KEY });
        
        const prompt = `You are an expert forensic AI text detector and fact-checker.
Analyze the following text. Determine the probability that it was generated by a Large Language Model (like ChatGPT, Claude, etc) versus written by a human.
Also, provide a one-sentence forensic analysis of your reasoning (e.g., noting robotic sentence structures, repetitive phrasing, or highly natural human nuances).

Respond strictly with a JSON object containing the following structure (do not include markdown tags like \`\`\`json):
{
  "aiDetectionScore": <number from 0 to 100 representing probability of being AI>,
  "isAiGenerated": <boolean true if score > 50>,
  "analysis": "<string explaining your reasoning in one sentence>"
}

Text to analyze:
"""
${text}
"""`;

        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: prompt,
            config: {
                responseMimeType: "application/json"
            }
        });

        // Parse the JSON response from Gemini
        const result = JSON.parse(response.text);
        return result;

    } catch (error) {
        console.error("Gemini API Error, using fallback:", error.message);
        return simulatedAiDetection(text);
    }
};

module.exports = { analyzeTextWithAI };
